name: build

on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "Set branch env"
        shell: bash
        run: |
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push to docker hub"
        shell: bash
        run: |
          cd src
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-${{ env.GIT_BRANCH }}:latest -f Dockerfile
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}/${{ env.GIT_BRANCH }}:latest
